// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StickyCart() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"/cart\" class=\"navbar bg-white sticky bottom-0 w-full border-t border-zinc-400 shadow-sm shadow-zinc-200 text-black\"><div class=\"flex flex-1 items-center gap-2\"><p class=\"font-semibold text-lg\">Total:</p><p id=\"cart-total\" class=\"text-lg \">$total</p></div><div class=\"flex-none\"><div id=\"sticky-cart-icon\" class=\"dropdown dropdown-end\"></div></div></a> <input type=\"hidden\" hx-get=\"/api/cart/count\" hx-target=\"#sticky-cart-icon\" hx-swap=\"innerHTML\" hx-trigger=\"load, loadCartCount from:body\"> <input type=\"hidden\" hx-get=\"/api/cart/total\" hx-target=\"#cart-total\" hx-swap=\"innerHTML\" hx-trigger=\"load, loadCartCount from:body\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
