// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package cartview

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Jalenarms1/sillysocks-GoTH/models"
	"github.com/Jalenarms1/sillysocks-GoTH/views/icons"
	"github.com/Jalenarms1/sillysocks-GoTH/views/layouts"
)

func Page(cart models.Cart) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input type=\"hidden\" hx-get=\"/api/cart/items\" hx-target=\"#cart-items-list\" hx-trigger=\"load\" hx-swap=\"innerHTML\"><div class=\"flex flex-col gap-2 p-4 min-h-screen text-black\"><div class=\"flex justify-between items-center\"><p class=\"text-3xl font-semibold mb-2\">Cart</p><div id=\"delete-items\" hx-put=\"/api/cart/items/delete\" hx-trigger=\"click\" hx-include=\"#del-ids\" hx-target=\"#cart-items-list\" hx-on=\"htmx:afterRequest:document.getElementById(&#39;check-all&#39;).checked=false\" class=\" w-8 h-8 bg-red-500 rounded-md text-white p-1 hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = icons.TrashCan().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"overflow-x-hidden max-h-[60vh] overflow-y-scroll shadow-sm shadow-zinc-400 \"><table class=\"table table-xs  max-w-full \"><!-- head --><thead><tr class=\"text-black\"><th>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(cart) > 0 {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label><input id=\"check-all\" type=\"checkbox\" class=\"checkbox bg-white  border border-black\"></label>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</th><th></th><th>Name</th><th>Total</th></tr></thead> <tbody id=\"cart-items-list\" class=\"border-b border-zinc-300\"><!-- row 1 --></tbody></table></div><div class=\"flex items-end justify-between gap-5\"><div id=\"price-list\" class=\"flex w-1/2 items-center mt-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = PriceList(cart).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"flex items-center w-1/2\"><button class=\"btn btn-warning flex items-center w-full\"><div class=\"w-6 h-6\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = icons.ShoppingBag().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><span class=\"text-base\">Checkout</span></button></div></div><input type=\"hidden\" hx-get=\"/api/cart/price-list\" hx-target=\"#price-list\" hx-swap=\"innerHTML\" hx-trigger=\"loadPriceList from:body\"> <input type=\"hidden\" id=\"del-ids\" name=\"productIds\" value=\"\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.App().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/public/cartview/index.js\" defer></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
